### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by KarenGarciaGarcia** [SistemasTecTlaxiaco/actividad-1-infografia-KarenGarciaGarcia#2]
[INFOGRAFÍA-Karen García García.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-KarenGarciaGarcia/files/12490452/INFOGRAFIA-Karen.Garcia.Garcia.pdf)

**Comment by Arlet04** [comment]
Partes de la infografía : 4
Coherencia: 3 
Organización: 4
Diseño: 3
Creatividad : 3
Calificación 17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
